# Generated by Django 2.1.4 on 2019-04-04 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/core')),
                ('won', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goal_for', models.IntegerField()),
                ('goal_against', models.IntegerField()),
                ('club_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagues', models.CharField(choices=[('english', 'english league'), ('spanish', 'spanish league'), ('italian', 'italian league'), ('french', 'french league'), ('german', 'german league'), ('champions', 'champions league'), ('egyptian', 'egyptian league')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(verbose_name='date published')),
                ('news_text', models.TextField()),
                ('news_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/core')),
                ('league_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.League')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='leaguenews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.LeagueNews'),
        ),
        migrations.AddField(
            model_name='club',
            name='league_names',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='core.League'),
        ),
    ]
