# Generated by Django 2.1.4 on 2019-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='draw',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='won',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='league',
            name='leagues',
            field=models.CharField(choices=[('الدوري الانجليزي', 'english league'), ('الدوري الاسباني', 'spanish league'), ('الدوري الايطالي', 'italian league'), ('الدوري الفرنسي', 'french league'), ('الدوري الالماني', 'german league'), ('دوري ابطال اوروبا', 'champions league'), ('الدوري المصري', 'egyptian league')], max_length=100),
        ),
    ]
