# Generated by Django 2.1.4 on 2019-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190408_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='leagues',
            field=models.CharField(choices=[('english', 'english league'), ('spanish', 'spanish league'), ('italian', 'italian league'), ('french', 'french league'), ('german', 'german league'), ('champions', 'champions league'), ('egyptian', 'egyptian league')], max_length=100),
        ),
    ]
