# Generated by Django 2.1.4 on 2019-04-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_club_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='points',
        ),
    ]
