# Generated by Django 2.1.4 on 2019-04-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_club_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='year_of_establishment',
            field=models.IntegerField(default=1900),
        ),
    ]
