# Generated by Django 2.1.4 on 2019-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_club_year_of_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguenews',
            name='clubs',
            field=models.ManyToManyField(related_name='news', to='core.Club'),
        ),
    ]
