# Generated by Django 2.1.4 on 2019-04-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190416_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateTimeField(verbose_name='play date')),
                ('score_visitor', models.IntegerField()),
                ('score_local', models.IntegerField()),
                ('club_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_club_local', to='core.Club')),
                ('club_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_club_visitor', to='core.Club')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.League')),
            ],
        ),
    ]
