# Generated by Django 2.1.4 on 2019-04-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='core.League'),
        ),
    ]
