# Generated by Django 2.1.4 on 2019-04-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190416_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='name_ar',
            field=models.CharField(default='الدوري', max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
