# Generated by Django 2.1.4 on 2019-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190428_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name_ar',
            field=models.CharField(default='الدوري', max_length=100),
        ),
    ]
