# Generated by Django 2.1.4 on 2019-04-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190428_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_position',
        ),
    ]
