# Generated by Django 2.1.4 on 2019-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_club_club_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='goal_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='goal_for',
            field=models.IntegerField(default=0),
        ),
    ]
